/*
 *          ::::::::  :::       :::     :::     :::::::::  :::::::::   ::::::::
 *         :+:    :+: :+:       :+:   :+: :+:   :+:    :+: :+:    :+: :+:    :+:
 *         +:+    +:+ +:+       +:+  +:+   +:+  +:+    +:+ +:+    +:+ +:+    +:+
 *         +#+    +:+ +#+  +:+  +#+ +#++:++#++: +#+    +:+ +#++:++#:  +#+    +:+
 *         +#+  # +#+ +#+ +#+#+ +#+ +#+     +#+ +#+    +#+ +#+    +#+ +#+    +#+
 *         #+#   +#+   #+#+# #+#+#  #+#     #+# #+#    #+# #+#    #+# #+#    #+#
 *          ###### ###  ###   ###   ###     ### #########  ###    ###  ########
 *
 *        Q W A D R O   V I D E O   G R A P H I C S   I N F R A S T R U C T U R E
 *
 *                               (c) 2017 SIGMA FEDERATION
 *                               ESTADO-MAIOR DA SEGURIDADE
 *                                 SIGMA TECHNOLOGY GROUP
 *                                        ENGITECH
 */

// This code is part of SIGMA GL/2.
// This software is part of Advanced Video Graphics Extensions.

#ifndef AFX_DRAW_CONTEXT_H
#define AFX_DRAW_CONTEXT_H

#include "qwadro/afxIoBridge.h"

typedef enum afxCmdFlag
{
    // Commands will be submitted more than once only and then automatically invalidated.
    afxCmdFlag_RECURRENT = AFX_BITMASK(0),

    // Commands will be side-loaded (inlined) by a front context.
    afxCmdFlag_INCURRENT = AFX_BITMASK(1),

    // Commands will be shared across more than one DPU concurrently.
    afxCmdFlag_CONCURRENT = AFX_BITMASK(2),

    // Commands are considered entirely inside a IOing scope (to be used by a front context).
    afxCmdFlag_SCOPED = AFX_BITMASK(3)
} afxCmdFlags;

typedef enum afxIoContextFlag
{
    // The command streams generated by the context are expected to be ephemeral, meaning that they will become invalidated in a relatively short timeframe. 
    // This flag is intended to be used by the implementation to optimize memory management.
    afxContextFlag_TRANSIENT    = AFX_BITMASK(0),

    // The command streams generated by the context are NOT able to be individually reset.
    afxContextFlag_MONOLITHIC   = AFX_BITMASK(1),

    // The command streams generated by the context are protected.
    afxContextFlag_PROTECTED    = AFX_BITMASK(2),
} afxIoContextFlags;

AFX_DEFINE_STRUCT(afxIoContextConfig)
{
    afxAptitude     caps;

    afxMask         exuMask;

    afxIoContextFlags flags;

    afxCmdFlags     cmdFlags;

    afxUnit         auxCnt;

    // The capacity of recycle queue.
    afxUnit         recycCap;

    void*           udd;

    afxString       tag;
};

/*
    The AfxAcquireIoContexts() function allocates multiple IO contexts (which could be command buffers
    or command contexts) for recording IOing commands for a specified IO system.

    This function allocates @cnt IO contexts (command buffers) and returns them in the @contexts[] array.
    If the allocation of any of the IO contexts fails, all successfully allocated IO contexts are freed and set to NIL.
    The function returns an error code if any allocation fails.
*/

AFX afxError AfxAcquireIoContexts
(
    // The IO system to provide the IOing contexts.
    afxIommu iom,

    // An optional base context to provide a shared command pool.
    afxIoContext pool,

    // The information specifying the operation context.
    afxIoContextConfig const* info,

    // The count of the IO contexts wanted to be allocated.
    afxUnit cnt,

    // An array of IO contexts to be allocated.
    afxIoContext contexts[]
);

/*
    The AfxRecycleIoContexts() function recycles IO contexts, releasing resources or allowing for reuse.
    This function is used to opportunistically try to recycle IO contexts (potentially preserving allocations) or destroy it.

    A flag can be used to indicate whether all or most of the resources owned by the context should be reclaimed by the system.
    If this flag is not set, then the IO context may hold onto memory resources and reuse them when recording commands.
*/

AFX afxError AfxRecycleIoContexts
(
    // A flag that indicates whether all or most of the resources owned by the batch should be reclaimed by the system.
    afxBool freeRes,

    // The number of contexts to be disposed.
    afxUnit cnt,

    // The IO context that holds the commands.
    afxIoContext contexts[]
);

/*
    The AfxExecuteIoCommands() function submits multiple IO commands to the devices briged to the IO system for execution.
    It allows for synchronized execution using a fence object, ensuring that commands are executed in the proper order.
    This function is useful in graphics systems where multiple command streams need to be processed,
    and synchronization between CPU and GPU tasks is required. By managing the submission through a control structure
    and using a fence for synchronization, the function ensures that commands are executed efficiently and correctly.
*/

AFX afxError AfxExecuteIoCommands
(
    // The IO system where the IO commands will be executed.
    afxIommu iom,

    // The number of IO contexts to be executed.
    // This tells the function how many contexts in the @contexts array should be processed.
    afxUnit cnt,

    // A control structure that might define various parameters related to how the IO commands are submitted, 
    // such as synchronization or execution order. This encapsulate details like submission flags, 
    // command queues, or context properties that manage how and when the IO commands are executed.
    afxSubmission const submissions[],

    afxUnit queueingMap[]
);

////////////////////////////////////////////////////////////////////////////////

AFX afxMask AfxGetIoCommandPort
(
    afxIoContext ctx,

    afxMask exuMask
);

AFX afxAptitude AfxGetIoCommandAptitude
(
    afxIoContext ctx, 

    afxAptitude caps
);

AFX afxIoContext AfxGetIoCommandPool
(
    afxIoContext ctx
);

AFX afxCmdId AfxGetLastIoCommandId
(
    afxIoContext ctx
);

AFX afxCmdId AfxGetNextIoCommandId
(
    afxIoContext ctx
);

/*
    Exhausting a IO context recycles all of the resources from all of the auxiliary contexts allocated from the pool context back to the pool context. All IO contexts that have been allocated from the pool context are put in the initial state.
*/

AFX afxError AfxExhaustIoContext
(
    afxIoContext ctx,

    afxBool freeMem
);

/*
    Reset a IO context to the initial state.
    Any primary IO context that is in the recording or executable state and has @ctx recorded into it, becomes invalid.
*/

AFX afxError AfxPrepareIoCommands
(
    // The IO context which the batch will be allocated from.
    afxIoContext ctx, 

    afxBool purge,

    afxCmdFlags flags
);

/*
    Finish recording a IO context.
*/

AFX afxError AfxCompileIoCommands
(
    // The IO context recording commands.
    afxIoContext ctx
);

  //////////////////////////////////////////////////////////////////////////////
 // BASIC COMMANDS                                                           //
//////////////////////////////////////////////////////////////////////////////

/*
    AfxCmdCommenceDebugScope(), AfxCmdConcludeDebugScope(), and AfxCmdMarkDebugMilestone().

    These functions let you annotate a IO context (afxIoContext) with debug scopes and milestones.
    Tools like GPU debuggers, frame analyzers, profilers, or custom logging systems can use these annotations to show:
     - hierarchical regions of GPU work
     - named events or markers
     - color-coded debug ranges

    They do not affect rendering but make GPU command streams easier to inspect.
*/

/*
    The AfxCmdCommenceDebugScope() method starts (opens) a debug scope within the IO context.
    It marks the beginning of a labeled section of GPU work.
    All commands recorded after this call will be considered part of this debug region until AfxCmdConcludeDebugScope is called.
*/

AFX afxError AfxCmdCommenceDebugScope
(
    // The IO context being annotated.
    afxIoContext ctx,

    // A string label for the region (e.g., "Shadow Pass").
    afxString const*name,

    // Optional color to visually represent this region in debugging tools.
    afxV4d const color
);

/*
    The AfxCmdConcludeDebugScope() ends (closes) the most recently opened debug scope.
    It completes the region started by AfxCmdCommenceDebugScope.
    Scopes must be properly nested and balanced.

*/

AFX afxError AfxCmdConcludeDebugScope
(
    // The IO context being annotated.
    afxIoContext ctx
);

/*
    The AfxCmdMarkDebugMilestone() method inserts a single debug marker at the current point in the command stream.
    It does not create a region. It represents an instantaneous "event" or "checkpoint" in the GPU command flow.
    Shows up as a point marker in profilers or debugging tools.
*/

AFX afxError AfxCmdMarkDebugMilestone
(
    // The IO context being annotated.
    afxIoContext ctx,

    // A string that describes what the milestone represents (e.g., "Upload Complete").
    afxString const*name,

    // Optional color for the marker.
    afxV4d const color
);

/*
    The AfxCmdExecuteIoCommands() method records a command into a primary IO context (ctx) that causes a list of secondary IO contexts (aux[]) to be executed when the primary context is submitted.
    This is essentially the same concept as secondary command buffers in Vulkan or D3D12 bundles.

    Primary IO context is the main command stream you submit to the GPU.
    Secondary IO context is composed of pre-recorded command sequences which can be reused or inserted into primaries.
    AfxCmdExecuteIoCommands() inserts these secondary sequences into the primary command flow.

    A secondary that does not have the "simultaneous use" capability can only be used by one primary at a time.
    If you try to use it in multiple primaries at once, the engine invalidates the others to prevent undefined behavior.
    This is nearly identical to Vulkan's VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT.
    Why this exists? A non-simultaneous-use secondary may contain internal state that cannot be safely reused while
    it is already queued or being recorded in another context.

    If the nested IO context feature is enabled it is valid usage for AfxCmdExecuteIoCommands() to also be recorded to a secondary IO context.
    This means:
     - Secondary contexts can contain calls to AfxCmdExecuteIoCommands.
     - In other words, secondary-of-secondary nesting is allowed if enabled.
     - You can build hierarchies of reusable command sequences.
    This matches Vulkan’s inheriting and nested secondary command buffer support.
*/

AFX afxError AfxCmdExecuteIoCommands
(
    // The IO context that will side-load other contexts.
    afxIoContext ctx,

    // The number of auxiliary contexts to be inlined.
    afxUnit cnt,

    // An ordinal array of @cnt auxiliary IO context handles, which are recorded to execute in the main IO context.
    afxIoContext auxs[]
);

#endif//AFX_IO_CONTEXT_H
